"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 23:23:18.139737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('activity_days',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('workout_done', sa.Boolean(), nullable=False),
    sa.Column('workout_minutes', sa.Integer(), nullable=False),
    sa.Column('workout_type', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('steps BETWEEN 0 AND 200000', name=op.f('ck_activity_days_steps_range')),
    sa.CheckConstraint('workout_minutes BETWEEN 0 AND 600', name=op.f('ck_activity_days_workout_minutes_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_days_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_days')),
    sa.UniqueConstraint('user_id', 'day', name='uq_activity_days_user_day')
    )
    with op.batch_alter_table('activity_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_days_user_id'), ['user_id'], unique=False)

    op.create_table('ai_plans',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('fallback_reason', sa.String(length=40), nullable=True),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_plans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_plans'))
    )
    with op.batch_alter_table('ai_plans', schema=None) as batch_op:
        batch_op.create_index('ix_ai_plans_user_date', ['user_id', 'plan_date'], unique=False)

    op.create_table('profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=60), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('daily_study_goal_minutes', sa.Integer(), nullable=False),
    sa.Column('daily_step_goal', sa.Integer(), nullable=False),
    sa.Column('daily_task_goal', sa.Integer(), nullable=False),
    sa.Column('preferred_workout_time', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("preferred_workout_time IN ('morning', 'afternoon', 'evening')", name=op.f('ck_profiles_workout_time')),
    sa.CheckConstraint('daily_step_goal BETWEEN 0 AND 100000', name=op.f('ck_profiles_step_goal_range')),
    sa.CheckConstraint('daily_study_goal_minutes BETWEEN 0 AND 960', name=op.f('ck_profiles_study_goal_range')),
    sa.CheckConstraint('daily_task_goal BETWEEN 0 AND 50', name=op.f('ck_profiles_task_goal_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_profiles'))
    )
    op.create_table('subjects',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subjects_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('user_id', 'name', name='uq_subjects_user_name')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_user_id'), ['user_id'], unique=False)

    op.create_table('tasks',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high')", name=op.f('ck_tasks_priority')),
    sa.CheckConstraint("status IN ('todo', 'done')", name=op.f('ck_tasks_status')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tasks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('ix_tasks_user_completed_at', ['user_id', 'completed_at'], unique=False)
        batch_op.create_index('ix_tasks_user_status_due', ['user_id', 'status', 'due_date'], unique=False)

    op.create_table('backlog_items',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('backlog', 'revision')", name=op.f('ck_backlog_items_kind')),
    sa.CheckConstraint("status IN ('pending', 'done')", name=op.f('ck_backlog_items_status')),
    sa.CheckConstraint('estimated_minutes BETWEEN 5 AND 600', name=op.f('ck_backlog_items_estimate_range')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_backlog_items_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_backlog_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backlog_items'))
    )
    with op.batch_alter_table('backlog_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backlog_items_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index('ix_backlog_items_user_status', ['user_id', 'status'], unique=False)

    op.create_table('exams',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_exams_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exams_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exams'))
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index('ix_exams_user_date', ['user_id', 'exam_date'], unique=False)

    op.create_table('study_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('backlog_item_id', sa.Uuid(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('duration_minutes BETWEEN 1 AND 720', name=op.f('ck_study_sessions_duration_range')),
    sa.ForeignKeyConstraint(['backlog_item_id'], ['backlog_items.id'], name=op.f('fk_study_sessions_backlog_item_id_backlog_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_study_sessions_subject_id_subjects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_sessions'))
    )
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_sessions_backlog_item_id'), ['backlog_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_sessions_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index('ix_study_sessions_user_date', ['user_id', 'session_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_study_sessions_user_date')
        batch_op.drop_index(batch_op.f('ix_study_sessions_subject_id'))
        batch_op.drop_index(batch_op.f('ix_study_sessions_backlog_item_id'))

    op.drop_table('study_sessions')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index('ix_exams_user_date')
        batch_op.drop_index(batch_op.f('ix_exams_subject_id'))

    op.drop_table('exams')
    with op.batch_alter_table('backlog_items', schema=None) as batch_op:
        batch_op.drop_index('ix_backlog_items_user_status')
        batch_op.drop_index(batch_op.f('ix_backlog_items_subject_id'))

    op.drop_table('backlog_items')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_user_status_due')
        batch_op.drop_index('ix_tasks_user_completed_at')

    op.drop_table('tasks')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_user_id'))

    op.drop_table('subjects')
    op.drop_table('profiles')
    with op.batch_alter_table('ai_plans', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_plans_user_date')

    op.drop_table('ai_plans')
    with op.batch_alter_table('activity_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_days_user_id'))

    op.drop_table('activity_days')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
